
// src/app/(landing)/terms/page.tsx
"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="py-16 md:py-24 bg-background">
      <div className="container mx-auto px-4 max-w-3xl">
        <Card className="bg-card shadow-lg">
          <CardHeader>
            <CardTitle className="text-4xl font-bold text-foreground text-center">Terms of Service</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-sm text-center">Last Updated: {new Date().toLocaleDateString()}</p>
            
            <h2 className="text-2xl font-semibold text-foreground">1. Introduction</h2>
            <p>
              Welcome to Scholar Summarizer ("Service", "App"). These Terms of Service ("Terms") govern your use of our web application. 
              By accessing or using the Service, you agree to be bound by these Terms.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">2. Use of Service</h2>
            <p>
              Scholar Summarizer allows users to upload PDF documents for AI-powered summarization. You agree to use the Service only for lawful purposes and in accordance with these Terms.
            </p>
            <p>
              You are responsible for any content you upload and for ensuring you have the right to use and process such content.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">3. User Accounts & Data</h2>
            <p>
              To access certain features, you must register for an account. You are responsible for maintaining the confidentiality of your account credentials.
            </p>
            <p>
              User data, including uploaded PDFs and generated summaries, is handled as described in our Privacy Policy. PDFs are processed solely for the purpose of generating summaries and are not stored long-term unless explicitly saved by the user (feature optional).
            </p>
            <p>
              User profile information (UID, plan, quota, last summary date, admin status) is stored in Firebase Firestore.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">4. Quotas and Plans</h2>
            <p>
              The Service offers different plans (e.g., Free, Premium) with varying daily summarization quotas. We reserve the right to modify quotas and plan features at any time.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">5. Intellectual Property</h2>
            <p>
              The Service and its original content (excluding user-uploaded content), features, and functionality are and will remain the exclusive property of Scholar Summarizer and its licensors.
            </p>
            <p>
              Summaries generated by the AI are for your personal or academic use.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">6. Termination</h2>
            <p>
              We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">7. Limitation of Liability</h2>
            <p>
              In no event shall Scholar Summarizer, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
            
            <h2 className="text-2xl font-semibold text-foreground">8. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">9. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us via the contact information provided on our landing page.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
