
// src/app/(landing)/privacy/page.tsx
"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function PrivacyPage() {
  return (
    <div className="py-16 md:py-24 bg-background">
      <div className="container mx-auto px-4 max-w-3xl">
        <Card className="bg-card shadow-lg">
          <CardHeader>
            <CardTitle className="text-4xl font-bold text-foreground text-center">Privacy Policy</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-lg dark:prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-sm text-center">Last Updated: {new Date().toLocaleDateString()}</p>

            <h2 className="text-2xl font-semibold text-foreground">1. Introduction</h2>
            <p>
              Scholar Summarizer ("we", "us", "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our web application.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">2. Information We Collect</h2>
            <p>We may collect the following types of information:</p>
            <ul className="list-disc pl-6">
              <li>
                <strong>Personal Identification Information:</strong> When you register, we collect your email address. Your UID, plan type, daily quota, last summary date, and admin status are stored in Firebase Firestore.
              </li>
              <li>
                <strong>Uploaded Documents:</strong> When you upload a PDF, its text content is extracted and sent to the Gemini API for summarization. We process user PDFs only for summary purposes. These documents are not stored long-term by default unless you use an explicit "save summary" feature (if available), which would then store them in Firebase Storage.
              </li>
              <li>
                <strong>Generated Summaries:</strong> Summaries generated by the AI are displayed to you. They are not shared with third parties. If a "save summary" feature is used, they may be stored in Firebase Storage associated with your account.
              </li>
              <li>
                <strong>Usage Logs:</strong> We store usage logs (e.g., user ID, timestamp of summary generation, potentially the number of characters processed) for analytics, quota tracking, and service improvement. These logs are stored in Firebase Firestore.
              </li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground">3. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul className="list-disc pl-6">
              <li>Provide, operate, and maintain our Service.</li>
              <li>Manage your account and provide customer support.</li>
              <li>Process your PDF uploads and generate summaries.</li>
              <li>Monitor and enforce your daily quota.</li>
              <li>Improve our Service and develop new features.</li>
              <li>Monitor usage for analytics and security purposes.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground">4. Data Storage and Security</h2>
            <p>
              Your user profile information, usage logs, and optionally saved summaries are stored on Firebase (Firestore and Storage), which provides robust security measures.
            </p>
            <p>
              While we strive to use commercially acceptable means to protect your Personal Information, no method of transmission over the Internet or method of electronic storage is 100% secure.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">5. Data Sharing and Disclosure</h2>
            <p>
              We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties.
            </p>
            <p>
              Uploaded PDF content is sent to the Gemini API for processing. Google's use of this data is governed by their respective privacy policies and terms.
            </p>
            <p>
              We may disclose your information if required by law or in response to valid requests by public authorities.
            </p>
            
            <h2 className="text-2xl font-semibold text-foreground">6. Your Data Rights</h2>
            <p>
              You may have certain rights regarding your personal data, subject to local data protection laws. These may include the right to access, correct, or delete your personal data. Please contact us to exercise these rights.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">7. Children's Privacy</h2>
            <p>
              Our Service is not intended for use by children under the age of 13 (or a higher age threshold if stipulated by local laws). We do not knowingly collect personally identifiable information from children.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">8. Changes to This Privacy Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </p>

            <h2 className="text-2xl font-semibold text-foreground">9. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us via the contact information provided on our landing page.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
